spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  profiles:
    active: local

  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/playercounts}
    username: ${POSTGRES_USERNAME:playercounts}
    password: ${POSTGRES_PASSWORD:playercounts}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

poll-worker:
  scheduler-interval-ms: ${POLL_WORKER_INTERVAL_MS:15000}
  thread-pool-size: ${POLL_WORKER_THREAD_POOL_SIZE:25}
  minecraft-default-port: ${MINECRAFT_DEFAULT_PORT:25565}
  kafka-topic: ${POLL_WORKER_KAFKA_TOPIC:server-ping-results}

cloud:
  sqs:
    queue-url: ${SQS_QUEUE_URL:}
    aws-region: ${AWS_REGION:us-east-1}