spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

poll-worker:
  scheduler-interval-ms: ${POLL_WORKER_INTERVAL_MS:15000}
  thread-pool-size: ${POLL_WORKER_THREAD_POOL_SIZE:25}
  minecraft-default-port: ${MINECRAFT_DEFAULT_PORT:25565}
  kafka-topic: ${POLL_WORKER_KAFKA_TOPIC:server-ping-results}