package net.playercounts.pollworker.service;

import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class FakeServerRegistryService {

    public List<String> getTrackedServers() {
        return List.of(
                "donutsmp.net",
                "mc.hypixel.net",
                "geo.hivebedrock.network",
                "mco.cubecraft.net",
                "mcpvp.club",
                "play.lbsg.net",
                "hub.fadecloud.com",
                "go.mineberry.org",
                "play.megasmp.gg",
                "mc.minehut.com",
                "topy.pika.host",
                "play.wynncraft.com",
                "minemen.club",
                "hub.manacube.com",
                "play.applemc.fun",
                "play.oplegends.com",
                "play.gommehd.net",
                "topt.jartex.fun",
                "hub.mc-complex.com",
                "play.inpvp.net",
                "play.mineville.org",
                "play.cubecraft.net",
                "play.manacube.com",
                "zeqa.net",
                "hoplite.gg",
                "2b2t.org",
                "flowpvp.gg",
                "top.hylexmc.net",
                "play.enchanted.gg",
                "play.extremecraft.net",
                "mushmc.com",
                "org.earthmc.net",
                "play.opblocks.com",
                "hub.cobblegalaxy.com",
                "play.cobblemon.gg",
                "play.lemoncloud.org",
                "play.zetrex.net",
                "play.pvplegacy.net",
                "play.bendersmc.co",
                "mc.minepiece.net",
                "ms.lifestealsmp.com",
                "play.mccisland.net",
                "tms.chickencraft.nl",
                "ti.ultimis.net",
                "proxylink.nethergames.org",
                "play.pixelblockmc.com",
                "play.galaxite.net",
                "play.akumamc.net",
                "hub.penguin.gg",
                "play.crystalchaos.net",
                "play.cosmicreborn.com",
                "play.mmorealms.gg",
                "play.jackpotmc.com",
                "play.tulipsurvival.com",
                "play.sunrealms.net",
                "play.concordmc.net",
                "server.mcs.gg",
                "play.voidsent.net",
                "play.cobblemondelta.com",
                "play.stardix.com",
                "play.blocaria.net",
                "org.oneblocky.com",
                "mcs.mellowcraft.org",
                "allthemons.moddedmc.net",
                "varamc.xyz",
                "skyblock.net",
                "play.insanitycraft.net",
                "play.purevanilla.co",
                "sharpness.gg",
                "play.mysticmc.co",
                "org.twenture.net",
                "play.theminecart.net",
                "play.chunklock.com",
                "play.boxpvp.net",
                "mc.cosmosmc.org",
                "mcs.flaremc.org",
                "mcsrvs.flamefrags.com",
                "mc.netherite.gg",
                "play.loverfella.com",
                "pvp.land",
                "play.cyt.gg",
                "play.smashmc.co",
                "realmi.fi",
                "play.minefury.net",
                "mc.leonemc.net",
                "play.krypticmc.net",
                "play.rainyday.gg",
                "sunnysmp.net",
                "mc.poke-legends.com",
                "play.smilemorecraft.com",
                "cavepvp.com",
                "elevatemc.com",
                "og-network.net",
                "play.vanillaplus.net",
                "pog.foxcraft.net",
                "play.solarskies.net",
                "ms.zedarmc.com",
                "petalsmp.net",
                "play.advancius.net",
                "org.bosscraft.net",
                "play.wildwoodsmp.com",
                "mc.embers.gg",
                "play.citrussmp.net",
                "play.lokamc.com",
                "craft.snailcraftmc.com",
                "ms.augustamc.com",
                "mc.acemc.co",
                "mc.imaginefun.net",
                "play.ottersmp.com"
//                "play.valatic.net",
//                "org.berrysmp.net",
//                "unstablesmp.fun",
//                "mc.lotc.co",
//                "daisysmp.net",
//                "diplomaticamc.com",
//                "ms.simplesurvival.gg",
//                "play.frootlysmp.net",
//                "play.originrealms.com",
//                "play.cobblemonrivals.com",
//                "ms.pokehub.org",
//                "mc.noblerealms.com",
//                "schooldays.club",
//                "play.pokesaga.org",
//                "org.yummymc.net",
//                "tubnet.gg",
//                "join.performium.co",
//                "play.lifesteal.rip",
//                "hub.breezesmp.com",
//                "play.kobbledkarp.com",
//                "play.fishonmc.net",
//                "us.shotbow.net",
//                "minewave.net",
//                "ms.vulengate.com",
//                "mcs.vanillarealms.com",
//                "play.cobblemonislands.com",
//                "play.vanillarealms.com",
//                "play.apexcobblemon.com",
//                "play.daisydreams.xyz",
//                "mcs.cozysmp.com",
//                "ms.ccnetmc.com",
//                "mc.fairy-tales.uk",
//                "mso.vanillaeuropa.com",
//                "go.havoc.games",
//                "mcs.nebulamc.gg",
//                "play.vaultsmp.com",
//                "play.pokearena.net",
//                "ms.stranded.lol",
//                "play.saltymc.org",
//                "play.cobblemontown.com",
//                "mso.tulipsmp.com",
//                "pvprivals.net",
//                "play.togethercraft.online",
//                "play.silvermons.com",
//                "play.flamingomc.com",
//                "play.timolia.de",
//                "tavernmc.net",
//                "playheromc.com",
//                "play.earthpol.com",
//                "mmp.altusnetwork.net",
//                "play.cobbleland.com",
//                "play.cobbletwo.com",
//                "mcso.democracycraft.net",
//                "org.castiamc.com",
//                "warden.trappedmc.com",
//                "mc.thealater.com",
//                "play.happysmp.net",
//                "play.roanoke.network",
//                "mcs.haycube.net",
//                "rearth.xyz",
//                "mc.survivify.org",
//                "ms.pixelmonrealms.com",
//                "play.fruitysmp.com",
//                "buzz.metromc.net",
//                "mc.sunnysurvival.com",
//                "play.rulercraft.com",
//                "mc.cherrysurvival.com",
//                "mc.safesurvival.net",
//                "ms.sakurarealms.net",
//                "join.lilacmc.net",
//                "play.lyramc.net",
//                "pokecentral.org",
//                "oceanias.net",
//                "play.theseedmc.com",
//                "play.creativefun.net",
//                "mc.thecavern.net",
//                "play.maplewoodmc.com",
//                "brew.mc.gg",
//                "vintagesky.gg",
//                "buzz.stonksmc.com",
//                "play.solarciv.com",
//                "play.ecosmp.net",
//                "play.theatlasmc.net",
//                "play.bugmc.net",
//                "us.mineplex.com",
//                "play.hivemc.com",
//                "cosmicpvp.com",
//                "playhideaway.com",
//                "play.blossomcraft.org",
//                "play.genwars.com",
//                "play.wintercrestmc.com",
//                "cobble.pokeclash.com",
//                "play.ggsmp.net",
//                "mcs.eyserver.com",
//                "ms.fruitville.org",
//                "eu.catpvp.xyz",
//                "hylexmc.net",
//                "play.minecafe.org",
//                "bee.craftadia.com",
//                "vanillahub.net"
        );
    }

}