server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/playercounts
    username: playercounts
    password: playercounts

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true