spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: playercounts-status-consumer-group
      auto-offset-reset: earliest
  data:
    redis:
      host: localhost
      port: 6379